# Generated by Django 4.0.3 on 2022-05-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viajes',
            new_name='Vacaciones',
        ),
    ]
