# Generated by Django 4.0.3 on 2022-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hombres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('mascota', models.BooleanField()),
                ('club_futbol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mujeres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('mascota', models.BooleanField()),
                ('club_futbol', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cerrajero',
        ),
        migrations.DeleteModel(
            name='Futbolista',
        ),
    ]
