# Generated by Django 4.0.3 on 2022-05-11 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_rename_descripcion_viaje_vacaciones_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajes',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
